### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ghost** [jdjkelly/quant#1]
So far, awesome work. I want to help out, but a license is needed first. If you're thinking GPL, then I'd like to propose using the AGPLv3

**Comment by sdball** [comment]
I'm a big fan of the MIT license unless you are trying to monetize the software.

http://opensource.org/licenses/MIT

**Comment by gvkhna** [comment]
I'd like to second the MIT, or even BSD license, simply because of the permissiveness. GPL has too many strings attached for most developers (I've found). Personally I want to use quantify.io to keep the data in a more open location, but I feel GPL would encumber certain developers or businesses from adopting the project. Just my .02...

**Comment by ghost** [comment]
I'd say MIT is good, with the GPL I just thought I'd throw something out there - it's hard to contribute to something with no license.

**Comment by jdjkelly** [comment]
I think the spirit behind this project is data liberation and ownership. Both MIT/BSD and GPL are compatible with that spirit. They key difference, as I understand it, is a legal responsibility for contributions and modifications to be licensed  in the same way as the original code - to the benefit of everyone. The various versions of GPL communicate this responsibility differently. 

In many cases this makes developers hesitant to include GPL code in their own projects/products because of the possibility of needing to license the entire project as GPL. But I think this concern is largely restricted to projects of the "library" sort - where the principal purpose of the project is as a toolkit to be included in other projects vs standalone products like WordPress. I'm not sure that's the case here (yet, at least). 

All that said, it appears as though dual licensing is a real option. For some time, jQuery was licensed in this way. I'm going to investigate this option.

**Comment by jdjkelly** [comment]
Some interesting comments from the jQuery Foundation's move towards MIT-only: http://blog.jquery.com/2012/09/10/jquery-licensing-changes/

**Comment by gvkhna** [comment]
So from what I understand of the licensing, if you feel big business is "exploiting" your work when they use it for profit, then GPL is appropriate. If you simply want to make your work available for anyone to use, kind of in the "tradition" of open source, then a permissive license like MIT/BSD is appropriate. 

I believe GPL has some merits for what it's trying to accomplish, but certain developers don't want to be encumbered by licensing when they want to use an open source project with their own. While GPL might be inline with this projects goals, I can still see businesses simply not adopting this service because of GPL, which would be terrible. 

Here's an interesting question on SE about dual licensing. 

http://programmers.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website

The answerer talks about there being a separate GPL Affero license for a certain restriction, and with AGPL, and versioning, etc. I think GNU is missing the point of open source licensing and has turned the idea of GPL into a muddled mess, which is why many open source projects and businesses are moving to MIT/BSD only.

**Comment by jdjkelly** [comment]
Thanks for the input everyone.

Under the spirit of "least confusion", I've added the MIT license.
